[package]
name = "sblang"
version = "0.1.0"
authors = ["calum"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "*"